GET http://localhost:4000/api/class


###
POST http://localhost:4000/api/class
Content-Type: application/json

{
    "class_name" : "X MIA 1"
}

###
DELETE http://localhost:4000/api/class/1


###
GET  http://localhost:4000/api/total_class