GET http://localhost:4000/api/counselling


###
POST http://localhost:4000/api/counselling
Content-Type: application/json

{
    "studentId": 1,
    "classId": 3,
    "userId": 6,
    "student_problem": "Late assignments",
    "penalty": "Warning",
    "solution": "Extra tutoring",
    "counselling_date": "2024-08-03T05:28:16.000Z",
    "counselling_note": "Discussed issues with student"
}
