### Create a new user
POST http://localhost:4000/api/user
Content-Type: application/json

{
    "username": "johndoe11",
    "email": "yos@gmail.com",
    "password": "123",
    "role": "admin",
    "confPassword": "123"

}   



###
GET http://localhost:4000/api/total_user